In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [48]:
# Definición de un modelo de regresión linear simple
class SimpleLinearRegression(tf.Module):
    def __init__(self, input_dim = 1, name = None):
        super().__init__(name=None)
        # Definir e inicializar parametros
        rand_w = []
        for i in range(input_dim):
            rand_w.append(tf.random.normal([1]))
        rand_b = tf.random.normal([1])
        self.input_dim = input_dim
        self.w = []
        for i in range(input_dim):
            self.w.append(tf.Variable(rand_w[i], name = f'w{i}', dtype = tf.float32))
        self.b = tf.Variable(rand_b, name = 'b', dtype = tf.float32)        

    def __call__(self, x): 
        if(self.input_dim==1):
            y = tf.multiply(x, self.w[0]) + self.b
            return y
        else:
            y = 0         
            for i in range(self.input_dim):
                y = y + np.matmul(x, self.w) 
            y = y + self.b
            return y
#  y = np.matmul(x, self.w) + self.b

In [3]:
# Ruta al archivo csv
archivo_csv = 'Promedios.csv'

df = pd.read_csv(archivo_csv)

target = df.pop('Promedio')
tf_target = tf.convert_to_tensor(target, name="tf_promedio", dtype=tf.float32)

In [4]:
variables_1 = 'Departamento'
features_1 = df[variables_1]

features_1 = features_1.sample(frac=1).reset_index(drop=True)

tf_features_1 = tf.convert_to_tensor(features_1, name="tf_departamento", dtype=tf.float32)

In [27]:
variables_2 = ['Departamento', 'Semestre']
features_2 = df[variables_2]

features_2 = features_2.sample(frac=1).reset_index(drop=True)

tf_features_2 = tf.convert_to_tensor(features_2, name="tf_departamento_semestre", dtype=tf.float32)
print(tf_features_2.shape)

(150, 2)


In [12]:
variables_3 = ['Departamento', 'Semestre', 'Edad']
features_3 = df[variables_3]

tf_features_3 = tf.convert_to_tensor(features_3, name="tf_departamento_semestre_edad", dtype=tf.float32)
print(tf_features_3.shape)

(150, 3)


In [49]:
lin_reg_var1 = SimpleLinearRegression(input_dim=1, name="promedios_departamento")
lin_reg_var2 = SimpleLinearRegression(input_dim=2, name="promedios_departamento_semestre")
lin_reg_var3 = SimpleLinearRegression(input_dim=3, name="promedios_departamento_semestre_edad")

In [8]:
# Función de costo
def mse_loss(y, yp):
    e = y - yp
    se = tf.multiply(e, e)
    mse = tf.reduce_mean(se, axis=0)
    return mse


In [50]:
# Cálculo del gradiente con respecto al modelo (1 variable)
learning_rate = 0.001

epoch = 2000

print(f"w0:{lin_reg_var1.w[0].numpy()}, b: {lin_reg_var1.b.numpy()}")

for i in range(epoch):
    with tf.GradientTape() as gt:
        # Predicción
        Yp_1 = lin_reg_var1(tf_features_1)
        loss = mse_loss(tf_target, Yp_1)
        # Calculo de los gradientes    
        grads = gt.gradient(loss, lin_reg_var1.trainable_variables)
        # Aplicamos la regla de actualización del gradiente
        for g, v in zip(grads, lin_reg_var1.trainable_variables):       
            v.assign_sub(learning_rate * g) # One Step
        
        Yp = lin_reg_var1(tf_features_1)
        loss = mse_loss(tf_target, Yp)

print(f"w0:{lin_reg_var1.w[0].numpy()}, b: {lin_reg_var1.b.numpy()}, Costo: {loss}")

w0:[-0.02003748], b: [-1.4546971]
w0:[9.510069], b: [49.06845], Costo: 381.1529846191406


In [52]:
# Cálculo del gradiente con respecto al modelo (2 variables)
learning_rate = 0.001

epoch = 2

for i in range(epoch):
    with tf.GradientTape() as gt:
        # Predicción
        print(tf_features_2.shape)
        Yp_2 = lin_reg_var2(tf_features_2)
        print(Yp_2)
        loss = mse_loss(tf_target, Yp_2)
        # print(f"w0:{lin_reg_var2.w.numpy()}, b: {lin_reg_var2.b.numpy()}, Costo: {loss}")
        # Calculo de los gradientes
        grads = gt.gradient(loss, lin_reg_var2.trainable_variables)
        print(grads)
        print(lin_reg_var2.trainable_variables)
        # Aplicamos la regla de actualización del gradiente
        for g, v in zip(grads, lin_reg_var2.trainable_variables):
            v.assign_sub(learning_rate*g) # One Step      
        
        Yp = lin_reg_var2(tf_features_2)
        loss = mse_loss(tf_target, Yp)
        print(f"w0:{lin_reg_var2.w.numpy()}, b: {lin_reg_var2.b.numpy()}, Costo: {loss}")


(150, 2)
tf.Tensor(
[[31.690815]
 [53.84434 ]
 [42.880928]
 [35.370476]
 [31.690815]
 [31.690815]
 [42.880928]
 [31.690815]
 [53.84434 ]
 [46.409454]
 [53.617638]
 [42.729794]
 [38.899   ]
 [42.880928]
 [46.56059 ]
 [24.255926]
 [53.84434 ]
 [35.52161 ]
 [49.93798 ]
 [31.464111]
 [42.50309 ]
 [53.84434 ]
 [38.974564]
 [28.011154]
 [53.84434 ]
 [53.54207 ]
 [24.255926]
 [35.219337]
 [42.50309 ]
 [38.823433]
 [24.331493]
 [31.690815]
 [24.331493]
 [46.333885]
 [61.27923 ]
 [46.18275 ]
 [35.143772]
 [38.899   ]
 [42.57866 ]
 [49.93798 ]
 [46.18275 ]
 [46.333885]
 [38.899   ]
 [35.370476]
 [46.258316]
 [31.464111]
 [24.180359]
 [42.729794]
 [46.333885]
 [53.84434 ]
 [31.464111]
 [38.823433]
 [53.84434 ]
 [42.880928]
 [46.409454]
 [53.84434 ]
 [31.464111]
 [39.050133]
 [24.255926]
 [46.333885]
 [50.24025 ]
 [38.974564]
 [38.823433]
 [49.93798 ]
 [46.258316]
 [31.464111]
 [38.974564]
 [35.370476]
 [53.84434 ]
 [50.16468 ]
 [38.974564]
 [39.20127 ]
 [42.880928]
 [35.294907]
 [50.08911 ]
 [24.

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [60]:
# Cálculo del gradiente con respecto al modelo (3 variables)
learning_rate = 0.001

# batch_size = 1
# num_batches = tf_features_3.shape[0]//batch_size

epoch = 2000

for i in range(epoch):
    with tf.GradientTape() as gt:
        # Predicción
        Yp_3 = lin_reg_var3(tf_features_3)
        loss = mse_loss(tf_target, Yp_3)
        print(f"w0:{lin_reg_var3.w.numpy()}, b: {lin_reg_var3.b.numpy()}, Costo: {loss}")
        # Calculo de los gradientes
        grads = gt.gradient(loss, lin_reg_var3.trainable_variables)
        print(grads)
        print(lin_reg_var3.trainable_variables)
        # Aplicamos la regla de actualización del gradiente
        for g, v in zip(grads, lin_reg_var3.trainable_variables):
            v.assign_sub(learning_rate*g) # One Step        
        
        Yp = lin_reg_var2(tf_features_2)
        loss = mse_loss(tf_target, Yp)
        print(f"w0:{lin_reg_var3.w.numpy()}, b: {lin_reg_var3.b.numpy()}, Costo: {loss}")


w0:[-1.5777926  0.2733995  0.5663654], b: [0.22815959], Costo: 6740.66845703125
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-163.83513], dtype=float32)>, None)
(<tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([0.22815959], dtype=float32)>, <tf.Variable 'w:0' shape=(3,) dtype=float32, numpy=array([-1.5777926,  0.2733995,  0.5663654], dtype=float32)>)
G is  tf.Tensor([-163.83513], shape=(1,), dtype=float32)
V is  <tf.Variable 'b:0' shape=(1,) dtype=float32, numpy=array([0.22815959], dtype=float32)>
G is  None
V is  <tf.Variable 'w:0' shape=(3,) dtype=float32, numpy=array([-1.5777926,  0.2733995,  0.5663654], dtype=float32)>


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'